<?php
/**
 * @file
 * Functions for shield module
 */


/**
 * Implements hook_menu().
 */
function shield_menu() {
	$items = array();
	$items['admin/config/system/shield'] = array(
		'title' => 'Shield',
		'description' => 'Manage the settings of PHP Authentication shield.',
		'route_name' => 'shield_settings',
	);
	return $items;
}

/**
 * Implements hook_permission().
 */
function shield_permission() {
	return array(
		'administer shield' => array(
			'title' => t('Administer shield module'),
			'description' => t('Perform administration tasks for shield module.'),
		),
	);
}
